;HECHO POR ROBERTO SAN PEDRO
;PROGRAMA QUE CALCULA LA RAIZ CUADRADA DE UN NUMERO ENTRE 0 Y 99

;PROGRAMA PRINCIPAL
	.org 0000h
	LD B,29  ;numero que se le sacara raiz
	LD C,0  ;registro del resultado
	LD A,B  ;se carga el numero en registro A para todas las operaciones

	;-----------------------------
	;CASOS PREDETERMINADOS
	;-----------------------------

	CP 0
	JP Z, FIN1
	CP 1
	JP Z, FIN1

	;--------------
	;CICLO WHILE
	;--------------

	LD D,1 ;VARIABLE RESULT
	LD E,1 ;VARIABLE i
WHILE:
	LD A,B
	CP D
	JP C, FIN2 ;AL HACER LA COMPARACION Y A SEA MENOR SE ACTIVA CARRY DANDO FIN
	INC E
	;DECLARAMOS LOS REGISTROS PARA OPERACIONES DE MULTIPLICACION
	LD H,0
	LD L,0
MULT:
	LD A,L ;A SERA EL ACUMULADOR DE LA MULTIPLICACION (SUMA)
	ADD A,E
	LD L,A ;SE GUARDA VALOR ACUMULADO PARA UTILIZAR REGISTRO A
	INC H ;SE INCREMENTA EL CONTADOR
	LD A,E ;SE CARGA EL NUMERO DE VECES A MULTIPLICAR PARA COMPARAR
	CP H
	JP NZ, MULT ;MIENTRAS EL CONTADOR NO SEA IGUAL AL NUMERO DE VECES A MULTIPLICAR (REGISTRO E) SEGUIRA SUMANDO
	LD D,L ;SE CARGA EL RESULTADO DE LA MULTIPLICACION PARA LA COMPARACION EN EL WHILE
	JP WHILE

FIN1:
	LD C,A ;LA RAIZ DE 0 Y 1 ES EL MISMO NUMERO
	JP BCD_NUM

FIN2:
	DEC E ;EL CONTADOR ESTÁ UNA UNIDAD POR ARRIBA DEL RESULTADO POR LO QUE SE DECREMENTA
	LD C,E
	JP BCD_NUM

	;---------------------
	;CONVERTIR EL VALOR DE B EN NUMERO BCD DECIMAL
	;---------------------

BCD_NUM:
	LD A,B
	LD E,0 ;REGISTRO QUE ALMACENARÁ DECENAS
DIVLOOP:
	CP 10
	JR C, DONE ;AL COMPARAR CON 10 Y SI ES MENOR NO SE NECESITA HACER NADA
	SUB 10
	INC E ;SE INCREMENTARAN LAS DECENAS
	JR DIVLOOP

DONE:
	;A SERAN LAS UNIDADES Y E LAS DECENAS
	SLA E
	SLA E
	SLA E
	SLA E
	;SE REALIZARON LOS CUATRO DESPLAZAMIENTOS DE LOS 4 BITS DEL DIGITO
	OR E ;PROVOCA QUE SE COMBINEN LAS DECENAS CON LAS UNIDADES DE A
	LD B,A
	HALT

	.END





